### ISSUE TITLE
It doesn't do what it says, the examples would show this if you used better values

### ISSUE THREAD

**Issue by james-antill** [shomali11/parallelizer#1]
The timeout is just on the wait, not on the execution. Indeed if you change the example2 to put a sleep before done then you can see that they still run (this is easier if you also lower the minute waits within the functions).

**Comment by shomali11** [comment]
You are correct. I didn't mean to make it sound that the go-routines would be canceled.

The timeout is indeed on the wait. No cancellation occurs.

**Comment by shomali11** [comment]
I updated the example and documentation to show that the go-routines are not canceled.
